baseURL: 'https://divyansha-s.github.io'
languageCode: en-us
title: Divyansha Sehgal
theme: "PaperMod"

# profile mode on the theme

params:

    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Divyansha Sehgal
    keywords: [Website, Blog, Portfolio]


  # profile mode
    profileMode:
        enabled: true
        title: "Hi there, I'm Divyansha" # optional default will be site title
        subtitle: "Technology Policy & Program Management | Platform Governance, AI Governance, Cybersecurity"
        imageUrl: /img/pro pic.jpg # optional
        imageTitle: "profile image" # optional
        imageWidth: 170 # custom size
        imageHeight: 170 # custom size

    #social icons
    socialIcons: # optional
        - name: email
          url: "mailto:divyansha.ylt@gmail.com"
        - name: twitter
          url: "https://twitter.com/div_online"
        - name : medium
          url: "https://medium.com/@divyansha.sehgal"
        - name : linkedin
          url: "https://www.linkedin.com/in/divyansha-sehgal/"


# menu on the home page

menu:
    main:
        - identifier: home
          name: Home
          url: ''
          weight: 10
        - identifier: bio
          name: About
          url: /bio/
          weight: 20
        - identifier: research 
          name: Research 
          url: /research
          weight: 30
        - identifier: media 
          name: Media
          url: /essays
          weight: 40

